import React, { useState } from 'react';
import './RevenueEntryItems.css';
import ReactTooltip from 'react-tooltip';
import {revenueData} from './RevenuePage.jsx';

function RevenueEntryItems(props) {
    
    const[outputValue, setOutputValue] = useState('')
    
    return(
      <div className="revenue-entry-container">

        <div className="function-container">
          <p> Function </p>

          <div className="circle" id="circle1">
          <span id="entry"> Medical Center </span>
          <span id='toolTip1' className="tooltip" data-tip='A large, not-for-profit <br /> 
          regional medical center, <br /> 
          including multiple <br /> 
          hospitals, labs and <br /> 
          clinics. Income comes <br /> 
          from patients, medical <br /> 
          insurance companies, <br /> 
          and government <br /> 
          programs like medicare.'data-for='info-box'>
          <span>&#9432;</span></span>
          <ReactTooltip class="uwu" id='info-box' backgroundColor="#71A8FF"  textColor="black" place="bottom" event="click" html={true} globalEventOff="click" />
          </div>

          
          <div className="circle" id="circle2">
          <span id="entry"> Student Fees</span>
          <span className="tooltip" data-tip="Fees are dedicated to <br /> 
          specific services, such <br />
           as athletic facilities, <br /> 
           bus service (UNITRANS), <br /> 
           student organizations, <br /> 
           the CoHo and Student <br /> 
           Community Center, etc." data-for='info-box2'>
           &#9432;</span>
          <ReactTooltip id='info-box2' backgroundColor="#71A8FF" textColor="black" place="bottom" event="click" html={true} globalEventOff="click" />      
          </div>

          <div className="circle" id="circle3">
          <span id="entry"> State of California </span>
          <span className="tooltip" data-tip="General funds given <br /> 
           by the taxpayers of <br /> 
           California, appropriated <br /> 
           annually by the state <br /> 
           legislature. General <br /> 
           funds are not dedicated <br /> 
           to specific services." data-for='info-box3'>
           &#9432;</span>
          <ReactTooltip id='info-box3' backgroundColor="#71A8FF" textColor="black" place="bottom" event="click" html={true} globalEventOff="click" />      
          </div>


          <div className="circle" id="circle4">
          <span id="entry"> Tuition </span>
          <span className="tooltip" data-tip="Students pay tuition <br /> 
          to  attend the University. <br />
           Non-California residents <br />
          pay about twice as much as <br /> 
          residents. Tuition is also <br />
           general funds." data-for='info-box4'>&#9432;</span>
          <ReactTooltip id='info-box4' backgroundColor="#71A8FF" textColor="black" place="bottom" event="click" html={true} globalEventOff="click" />      
          </div>


          <div className="circle" id="circle5">
          <span id="entry"> Research Grants <br/> and Contracts</span>
          <span className="tooltip" data-tip="Government and industry <br /> 
          funds given to faculty <br /> 
          and graduate students <br /> 
          to perform research <br /> 
          projects. These include <br />
          up to 50% overhead in <br /> 
          addition to the cost <br /> 
          of the research." data-for='info-box5'>&#9432;</span>
          <ReactTooltip id='info-box5' backgroundColor="#71A8FF" textColor="black" place="bottom" event="click" html={true} globalEventOff="click" />      
          </div>


          <div className="circle" id="circle6">
          <span id="entry"> Pell Grants </span>
          <span className="tooltip" data-tip="Federal grants for <br /> 
          tuition and living <br /> 
          expenses for low-income <br />
          students. Percentage of <br /> 
          students with Pell grants <br />
          is a good way to <br /> 
          measure who a University <br /> 
          serves; at UCD, it's 34%; <br /> 
          at Cal Tech it's 14%; <br /> 
          at Sac State it's 71%." data-for='info-box6'>&#9432;</span>
          <ReactTooltip id='info-box6' backgroundColor="#71A8FF" textColor="black" place="bottom" event="click" html={true} globalEventOff="click" />      
          </div>


          <div className="circle" id="circle7">
          <span id="entry"> Non-educational<br/> Services </span>
          <span className="tooltip" data-tip="Services other than <br /> 
          education that people <br />
          pay for, like dorms, <br /> 
          dining, parking, etc. <br /> 
          At UC Davis, this <br /> 
          also includes almost <br /> 
          $500M of revenue <br /> 
          generated by medical <br /> 
          school faculty, or 8%, <br /> 
          making this category <br /> 
          look really big." data-for='info-box7'>&#9432;</span>
          <ReactTooltip id='info-box7' backgroundColor="#71A8FF" textColor="black" place="bottom" event="click" html={true} globalEventOff="click" />      
          </div>


          <div className="circle" id="circle8">
          <span id="entry"> Gifts, Endowments, <br/>  Interest, Etc. </span>
          <span className="tooltip" data-tip="Endowments are past <br />
          gifts that were invested <br /> 
          to provide income; <br /> 
          interest is earned on <br /> 
          other savings. The <br /> 
          Museum is the direct <br /> 
          result of a $10M gift <br /> 
          from Jan Shrem <br /> 
          and Maria Manetti <br /> 
          Shrem." data-for='info-box8'>&#9432;</span>
          <ReactTooltip id='info-box8' backgroundColor="#71A8FF" textColor="black" place="bottom" event="click" html={true} globalEventOff="click" />      
          </div>

          <div id="total">Total %</div>
      

        </div>

        <div className="percentage-container">
          <p id="percentage-wrap"> Percentage (%) </p>

          <input type="text" class="text-line" placeholder="0%" onKeyUp = {(e) =>{
            
            if (e.key === 'Enter'){
            props.indexValue(0);
            props.onKeyUp(e.target.value);
            e.target.value = e.target.value.replace(/\D/g,'') + '%';
            }
          }}/>
          <input type="text" class="text-line" placeholder="0%" onKeyUp = {(e) =>{
            if (e.key === 'Enter'){
            props.indexValue(1);
            props.onKeyUp(e.target.value);
            e.target.value = e.target.value.replace(/\D/g,'') + '%';
            }
          }}/>
          <input type="text" class="text-line" placeholder="0%" onKeyUp = {(e) =>{
            if (e.key === 'Enter'){
            props.indexValue(2);
            props.onKeyUp(e.target.value);
            e.target.value = e.target.value.replace(/\D/g,'') + '%';
            }
          }}/>
          <input type="text" class="text-line" placeholder="0%" onKeyUp = {(e) =>{
            if (e.key === 'Enter'){
            props.indexValue(3);
            props.onKeyUp(e.target.value);
            e.target.value = e.target.value.replace(/\D/g,'') + '%';
            }
          }}/>
          <input type="text" class="text-line" placeholder="0%" onKeyUp = {(e) =>{
            if (e.key === 'Enter'){
            props.indexValue(4);
            props.onKeyUp(e.target.value);
            e.target.value = e.target.value.replace(/\D/g,'') + '%';
            }
          }}/>
          <input type="text" class="text-line" placeholder="0%" onKeyUp = {(e) =>{
            if (e.key === 'Enter'){
            props.indexValue(5);
            props.onKeyUp(e.target.value);
            e.target.value = e.target.value.replace(/\D/g,'') + '%';
            }
          }}/>
          <input type="text" class="text-line" placeholder="0%" onKeyUp = {(e) =>{
            if (e.key === 'Enter'){
            props.indexValue(6);
            props.onKeyUp(e.target.value);
            e.target.value = e.target.value.replace(/\D/g,'') + '%';
            }
          }}/>
          <input type="text" class="text-line"  placeholder="0%" onKeyUp = {(e) =>{
            if (e.key === 'Enter'){
            props.indexValue(7);
            props.onKeyUp(e.target.value);
            e.target.value = e.target.value.replace(/\D/g,'') + '%';
            }
          }}/>
          <input type="text" class="text-line" placeholder="0%" readOnly="readonly" value={props.outputValue}/>
        </div>

      </div> 
    );
}

export default RevenueEntryItems;